// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsqvwpoqmkkzbggagtji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcXZ3cG9xbWtremJnZ2FndGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzAxODksImV4cCI6MjA2ODMwNjE4OX0.hMxTK2trM3wv1cPyBQhS0a5HMpEQCvPSZjwZ2T68tw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});